name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

  version_bump:
    name: Increment Version Before Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout the main branch to avoid detached HEAD state
        run: git checkout main

      - name: Extract current version from build.gradle.kts
        id: extract_version
        run: |
          VERSION=$(grep -oP 'versionName\s*=\s*"\K[0-9]+\.[0-9]+\.[0-9]+' app/build.gradle.kts)
          echo "Current version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Increment version number
        id: increment_version
        run: |
          VERSION="${{ steps.extract_version.outputs.version }}"
          PATCH=$(echo $VERSION | cut -d'.' -f3)
          MINOR=$(echo $VERSION | cut -d'.' -f2)
          MAJOR=$(echo $VERSION | cut -d'.' -f1)

          # Increment the patch version
          if [ "$PATCH" -lt 9 ]; then
            PATCH=$((PATCH + 1))
          else
            PATCH=0
            MINOR=$((MINOR + 1))
            # If the minor version goes up to 10, increment major version
            if [ "$MINOR" -eq 10 ]; then
              MINOR=0
              MAJOR=$((MAJOR + 1))
            fi
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"

          # Update the version in build.gradle.kts
          sed -i "s/versionName = \"$VERSION\"/versionName = \"$NEW_VERSION\"/" app/build.gradle.kts
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Commit version bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add app/build.gradle.kts
          git commit -m "Bump version to ${{ steps.increment_version.outputs.new_version }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

  build:
    name: Build Signed AAB
    needs: version_bump
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease

      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.ANDROID_DEVS_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_DEVS_ALIAS_PASSWORD }}

      - name: Upload AAB as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-aab
          path: app/build/outputs/bundle/release/app-release.aab